sudo: required
dist: trusty

language: python
python: "2.7"

env:
  - ANSIBLE_VERSION=latest
  - ANSIBLE_VERSION=2.3.2.0
  - ANSIBLE_VERSION=2.2.1.0
  - ANSIBLE_VERSION=2.1.0.0
  - ANSIBLE_VERSION=2.0.2.0
  - ANSIBLE_VERSION=2.0.0.0

before_install:
  - sudo apt-get update -qq
  - "[ -f get-dependencies.sh ] && sh -x get-dependencies.sh"
## serverspec test
  - sudo apt-get install -qq ruby2.0 rake
  - sudo gem2.0 install serverspec

install:
  # Install ansible.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"
  - "echo \"[test-kitchen]\nlocalhost\" > inventory"
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install --no-binary ansible ansible; else pip install --no-binary ansible ansible==$ANSIBLE_VERSION; fi

  # Check ansible version.
  - ansible --version

script:
  # Check the role/playbook's syntax.
  - ansible-playbook -i inventory test/integration/default/default.yml --syntax-check

  # Run the role/playbook with ansible-playbook.
  - ansible-playbook -i inventory --connection=local --sudo test/integration/default/default.yml -vvvv

  # Run the role/playbook again, checking to make sure it's idempotent.
  - >
    ansible-playbook -i inventory --connection=local --become test/integration/default/default.yml
    | tee /tmp/idempotency.log | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && cat /tmp/idempotency.log && exit 0)

# Serverspec
  - "cd test/integration/default/serverspec/ && bundle exec rake spec"

after_failure:
#  - "sudo systemctl -l status"
#  - "sudo journalctl -xe --no-pager"
  - "sudo tail -50 /var/log/syslog"
  - "service --status-all"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
