---

- name: Lufi cron - cleanbdd once a week
  ansible.builtin.cron:
    name: lufi cron cleanbdd
    weekday: '2'
    minute: '0'
    hour: '12'
    user: "{{ www_user }}"
    job: "cd {{ lufi_working_dir }}/ && carton exec script/lufi cron cleanbdd 2>&1 > /tmp/cron-lufi-cleanbdd"
    cron_file: ansible_lufi-cleanbdd

- name: Lufi cron - cleanfiles once a week
  ansible.builtin.cron:
    name: lufi cron cleanfiles
    weekday: '2'
    minute: '0'
    hour: '12'
    user: "{{ www_user }}"
    job: "cd {{ lufi_working_dir }}/ && carton exec script/lufi cron cleanfiles 2>&1 > /tmp/cron-lufi-cleanfiles"
    cron_file: ansible_lufi-cleanfiles

- name: Lufi cron - watch
  ansible.builtin.cron:
    name: lufi cron watch
    minute: '32'
    user: "{{ www_user }}"
    job: "cd {{ lufi_working_dir }}/ && carton exec script/lufi watch warn"
    cron_file: ansible_lufi-watch
