---

- name: Lufi | Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 86400
  changed_when: false
  when: ansible_os_family == 'Debian'
  register: pkg_result
  until: pkg_result is success

- name: Lufi | Install essential packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: "{{ lufi_pkg_deps }}"
  register: pkg_result
  until: pkg_result is success

# https://github.com/ansible/ansible/issues/16612
- name: Selinux ansible
  when: ansible_os_family == "RedHat"
  block:
    - name: Debug
      ansible.builtin.debug:
        var: ansible_selinux
    - name: RedHat | Ensure selinux dependencies are present
      ansible.builtin.package:
        name: libselinux-python
        state: present
      register: pkg_result
      until: pkg_result is success
    - name: Collect ansible facts again after selinux dependency install
      ansible.builtin.setup:
    - name: Debug
      ansible.builtin.debug:
        var: ansible_selinux
- name: Selinux
  when: ansible_os_family == "RedHat" and ansible_selinux.status is defined and ansible_selinux.status != 'disabled'
  block:
    - name: RedHat | Ensure selinux dependencies are present
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      with_items:
        - libselinux-python
        - libsemanage-python
        - policycoreutils-python
      register: pkg_result
      until: pkg_result is success

    - name: RedHat | Allow proxy to network connect in selinux
      ansible.posix.seboolean:
        name: httpd_can_network_connect
        state: true
        persistent: true

    - name: RedHat | Allow httpd to listen to unusual ports
      community.general.seport:
        ports: "{{ lufi_serverlisten }}"
        proto: tcp
        setype: http_port_t
        state: present
      when: lufi_serverlisten != 80 and lufi_serverlisten != 443

# - name: Lufi | Install cpanm
#   get_url:
#     url: https://cpanmin.us
#     dest: /usr/local/bin/cpanm
#     mode: 0555
#     checksum: 'sha256:453e68066f2faba5c9fe04b4ca47f915fe0001f71405560093a23919e5e30d65.'

- name: Lufi | Install Carton
  community.general.cpanm:
    name: Carton
    mirror: '{{ lufi_cpanm_mirror | default("https://cpan.metacpan.org/") }}'
  register: pkg_result
  until: pkg_result is success
