---

- name: Lufi | Update apt cache
  apt: update_cache=yes cache_valid_time=86400
  changed_when: no
  when: ansible_os_family == 'Debian'

- name: Lufi | Install essential packages
  package: name="{{ item }}" state=present
  with_items: "{{ lufi_pkg_deps }}"

# https://github.com/ansible/ansible/issues/16612
- block:
    - debug: var=ansible_selinux
    - name: RedHat | Ensure selinux dependencies are present
      package:
        name: libselinux-python
        state: present
    - action: setup
    - debug: var=ansible_selinux
  when: ansible_os_family == "RedHat"
- block:
    - name: RedHat | Ensure selinux dependencies are present
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - libselinux-python
        - libsemanage-python
        - policycoreutils-python

    - name: RedHat | Allow proxy to network connect in selinux
      seboolean:
        name: httpd_can_network_connect
        state: yes
        persistent: yes

# https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Managing_Confined_Services/sect-Managing_Confined_Services-Configuration_examples-Changing_port_numbers.html
# https://wiki.centos.org/HowTos/SELinux#head-ad837f60830442ae77a81aedd10c20305a811388
    - name: RedHat | Allow httpd to listen to unusual ports
      seport:
        ports: "{{ lufi_serverlisten }}"
        proto: tcp
        setype: http_port_t
        state: present
      when: lufi_serverlisten != 80 and lufi_serverlisten != 443
  when: ansible_os_family == "RedHat" and ansible_selinux

#- name: Lufi | Install cpanm
#  get_url:
#    url: https://cpanmin.us
#    dest: /usr/local/bin/cpanm
#    mode: 0555
#    checksum: 'sha256:453e68066f2faba5c9fe04b4ca47f915fe0001f71405560093a23919e5e30d65.'

- name: Lufi | Install Carton
  cpanm:
    name: Carton
