---

- name: Include version-specific variables for Ubuntu.
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  when: ansible_distribution == 'Ubuntu'
- name: Include version-specific variables for RedHat
  include_vars: "RedHat-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_os_family == "RedHat"
- name: Include version-specific variables for Alpine
  include_vars: "Alpine.yml"
  when: ansible_os_family == "Alpine"

- include: install.yml
  tags: lufi:install

- include: user.yml
  when: lufi_user != 'www-data'

- name: ensure .cpanm directory exists for lufi user
  file: dest={{ lufi_home }}/.cpanm state=directory owner={{ lufi_user }} mode=0700

  tags: lufi:site
- include: site.yml
  tags: lufi:site
  become: yes
  become_user: "{{ lufi_user }}"

## FIXME! kitchen/docker: ansible_service_mgr = sshd???
- debug: var=ansible_service_mgr
#- include: service-{{ ansible_service_mgr }}.yml
#  tags: lufi:service
#  when: ansible_service_mgr == 'sysvinit' or ansible_service_mgr == 'upstart' or ansible_service_mgr == 'systemd'
- include: service-systemd.yml
  when: ansible_distribution_release == 'xenial' or (ansible_os_family == "RedHat" and ansible_distribution_major_version == '7')
- include: service-upstart.yml
  when: ansible_distribution_release == 'trusty'
- include: service-sysvinit.yml
  when: ansible_distribution_release == 'precise' or (ansible_os_family == "RedHat" and ansible_distribution_major_version == '6')

- include: cron.yml
  tags: lufi:cron
- include: reverseproxy.yml

# for docker, start manually service
- name: docker | start lufi
  command: "/usr/local/bin/carton exec hypnotoad script/lufi"
  args:
    chdir: "{{ lufi_working_dir }}"
  become: yes
  become_user: "{{ lufi_user }}"
  when: not (ansible_service_mgr == 'sysvinit' or ansible_service_mgr == 'upstart' or ansible_service_mgr == 'systemd')
