---

- name: Debian | Ensure required apache modules are loaded
  community.general.apache2_module:
    state: present
    name: "{{ item }}"
  with_items:
    - headers
    - proxy
    - proxy_http
    - proxy_wstunnel
  when: lufi_reverseproxy is defined and lufi_reverseproxy == 'apache' and ansible_os_family == 'Debian'

- name: Nginx | Install lufi nginx reverseproxy configuration
  ansible.builtin.template:
    src: lufi-nginx.conf.j2
    dest: "{{ nginx_sitedir }}/lufi.conf"
    mode: '0644'
    backup: true
  when: lufi_reverseproxy is defined and lufi_reverseproxy == 'nginx'
  notify:
    - Restart nginx

- name: Debian | enable nginx reverseproxy
  ansible.builtin.file:
    src: "{{ nginx_sitedir }}/lufi.conf"
    dest: "/etc/nginx/sites-enabled/lufi.conf"
    state: 'link'
  when: lufi_reverseproxy is defined and lufi_reverseproxy == 'nginx' and ansible_os_family == 'Debian'
  notify:
    - Restart nginx

- name: Apache | Install lufi apache reverseproxy configuration
  ansible.builtin.template:
    src: lufi-apache.conf.j2
    dest: "{{ apache_sitedir }}/lufi.conf"
    mode: '0644'
    backup: true
  when: lufi_reverseproxy is defined and lufi_reverseproxy == 'apache'

- name: Debian | enable lufi apache reverseproxy configuration
  ansible.builtin.file:
    src: "{{ apache_sitedir }}/lufi.conf"
    dest: "/etc/apache2/sites-enabled/lufi.conf"
    state: 'link'
  when: lufi_reverseproxy is defined and lufi_reverseproxy == 'apache' and ansible_os_family == 'Debian'
  notify:
    - Restart apache
