---

- set_fact:
    lufi_proxy: yes

- name: install lufi nginx reverseproxy configuration
  template:
    src: lufi-nginx.conf.j2
    dest: "{{ nginx_sitedir }}/lufi.conf"
    mode: '0644'
    backup: yes
  when: lufi_reverseproxy is defined and lufi_reverseproxy == 'nginx'
  notify:
    - restart nginx
- name: Debian | enable nginx reverseproxy
  file:
    src: "{{ nginx_sitedir }}/lufi.conf"
    dest: "/etc/nginx/sites-enabled/lufi.conf"
    state: 'link'
  when: lufi_reverseproxy is defined and lufi_reverseproxy == 'nginx' and ansible_os_family == 'Debian'
  notify:
    - restart nginx

- name: install lufi apache reverseproxy configuration
  template:
    src: lufi-apache.conf.j2
    dest: "{{ apache_sitedir }}/lufi.conf"
    mode: '0644'
    backup: yes
  when: lufi_reverseproxy is defined and lufi_reverseproxy == 'apache'

