---

- name: Lufi | Copy sysvinit service config
  ansible.builtin.template:
    src: etc/default/lufi.j2
    dest: /etc/default/lufi
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart lufi

- name: Lufi | Copy sysvinit config
  ansible.builtin.command:
    cmd: cp {{ lufi_working_dir }}/utilities/lufi.init /etc/init.d/lufi
  args:
    creates: /etc/init.d/lufi
