---

- name: Lufi | Copy upstart service config
  ansible.builtin.template:
    src: etc/default/lufi.j2
    dest: /etc/default/lufi
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart lufi

- name: Lufi | Copy upstart config
  ansible.builtin.command: "cp {{ lufi_working_dir }}/utilities/lufi_upstart.conf /etc/init/lufi.conf"
  args:
    creates: /etc/init/lufi.conf
