---

- name: Lufi | Copy upstart service config
  template:
    src: etc/default/lufi.j2
    dest: /etc/default/lufi
    owner: root
    group: root
    mode: 0644
  notify: restart lufi

- name: Lufi | Copy upstart config
  command: cp {{ lufi_working_dir }}/utilities/lufi_upstart.conf /etc/init/lufi.conf
  args:
    creates: /etc/init/lufi.conf
