---

- name: Lufi | Copy sysvinit service config
  template:
    src: etc/default/lufi.j2
    dest: /etc/default/lufi
    owner: root
    group: root
    mode: 0644
  notify: restart lufi

- name: Lufi | Copy sysvinit config
  command: creates=/etc/init.d/lufi cp {{ lufi_working_dir }}/utilities/lufi.init /etc/init.d/lufi
