---

- name: Lufi | Create working directory
  file:
    dest: "{{ lufi_working_dir }}"
    state: directory

- name: Lufi | Checkout git repository
  git:
    repo: https://framagit.org/noplanman/lufi.git
    dest: "{{ lufi_working_dir }}"
    update: "{{ lufi_keep_updated }}"
    force: yes
  register: lufi_git_updated
  notify: restart lufi

- name: Lufi | Copy config
  template:
    src: lufi.conf.j2
    dest: "{{ lufi_working_dir }}/lufi.conf"
    mode: 0644
  notify: restart lufi

- name: Lufi | Install lufi
  command: carton install
  args:
    chdir: "{{ lufi_working_dir }}"
    creates: "{{ lufi_db_path }}"
  when: lufi_git_updated.changed
  register: lufi_app_installed
  notify: restart lufi

- name: Lufi | Update lufi
  command: carton update
  args:
    chdir: "{{ lufi_working_dir }}"
  when: not lufi_app_installed.changed and lufi_keep_updated
  register: lufi_app_updated
  changed_when: "'Successfully installed' in lufi_app_updated.stdout"
  notify: restart lufi

- name: Lufi | Set permissions on working directory
  file:
    path: "{{ lufi_working_dir }}"
    state: directory
    owner: "{{ lufi_user }}"
    group: "{{ lufi_group }}"
    recurse: yes
