---

- name: Lufi | Checkout git repository
  git:
     repo: https://framagit.org/fiat-tux/hat-softwares/lufi.git
#    repo: https://github.com/ldidry/lufi.git
#    repo: https://framagit.org/noplanman/lufi.git
    dest: "{{ lufi_working_dir }}"
    update: "{{ lufi_keep_updated }}"
    version: "{{ lufi_version | default('0.03') }}"
    force: yes
  register: lufi_git_updated
  changed_when: lufi_git_updated.after != lufi_git_updated.before
  notify:
    - restart lufi
- debug: var=lufi_git_updated
#- fail: msg=stop

- include: random.yml

- set_fact:
    lufi_proxy: yes
  when: lufi_reverseproxy is defined and (lufi_reverseproxy == 'nginx' or lufi_reverseproxy == 'apache')

## FIXME! any option to validate config?
- name: Lufi | Copy config
  template:
    src: lufi.conf.j2
    dest: "{{ lufi_working_dir }}/lufi.conf"
    mode: 0644
#    validate: 'cmd %s'
  notify:
    - restart lufi

## FIXME! command fails on trusty, not creating lufi.db
- name: Lufi | Install lufi
  command: "carton install {{ lufi_carton_install_args }}"
  args:
    chdir: "{{ lufi_working_dir }}"
    creates: "{{ lufi_db_path }}"
  environment:
    PATH: '/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin'
  register: lufi_app_installed
  notify:
    - restart lufi

- name: Lufi | Update lufi
  command: carton update
  args:
    chdir: "{{ lufi_working_dir }}"
  environment:
    PATH: '/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin'
  when: lufi_app_installed.changed or lufi_keep_updated
  register: lufi_app_updated
  changed_when: "'Successfully installed' in lufi_app_updated.stdout"
  notify:
    - restart lufi
## FIXME! fail on centos7 'Could not find module Apache::Htpasswd.'
  ignore_errors: true

#- name: Lufi | Set ownership on working directory
#  file:
#    path: "{{ lufi_working_dir }}"
#    state: directory
#    owner: "{{ lufi_user }}"
#    group: "{{ lufi_group }}"
#    recurse: yes
#  changed_when: no
