---

- name: Ensure lufi group exists
  ansible.builtin.group:
    name: "{{ lufi_group }}"

- name: Ensure lufi user exists
  ansible.builtin.user:
    name: "{{ lufi_user }}"
    groups: "{{ lufi_group }}"
    append: true
    home: "{{ lufi_home }}"
