---

- name: reload lufi systemd daemons
  command: systemctl daemon-reload
  notify: restart lufi
  when: ansible_service_mgr == 'systemd'

- name: restart lufi
  service: name=lufi state=restarted enabled=yes
  when: ansible_service_mgr == 'sysvinit' or ansible_service_mgr == 'upstart' or ansible_service_mgr == 'systemd'

- name: restart nginx
  service: name=nginx state=restarted
