---

- name: reload systemd daemon
  systemd:
    daemon_reload: yes
  when: >
    ansible_service_mgr == 'systemd' and
    not (ansible_virtualization_type is defined and ansible_virtualization_type == "docker")

- name: restart lufi
  service: name=lufi state=restarted enabled=yes
  when: ansible_service_mgr == 'sysvinit' or ansible_service_mgr == 'upstart' or ansible_service_mgr == 'systemd'

- name: restart nginx
  service: name=nginx state=restarted
